Repository Netflix/conductor, pull requests merged in 2021-04, with the labels that each got.

#2166 added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_question.md
  .github/workflows/ci.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: skip-changelog

#2159 Removed unimportant and potentially expensive APIs
  .github/ISSUE_TEMPLATE/bug.md
  client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
  core/src/main/java/com/netflix/conductor/service/AdminService.java
  core/src/main/java/com/netflix/conductor/service/AdminServiceImpl.java
  core/src/main/java/com/netflix/conductor/service/EventService.java
  core/src/main/java/com/netflix/conductor/service/EventServiceImpl.java
  core/src/test/java/com/netflix/conductor/service/EventServiceTest.java
  grpc-client/src/main/java/com/netflix/conductor/client/grpc/TaskClient.java
  grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/EventServiceImpl.java
  grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/TaskServiceImpl.java
  grpc/src/main/proto/grpc/event_service.proto
  grpc/src/main/proto/grpc/task_service.proto
  rest/src/main/java/com/netflix/conductor/rest/controllers/AdminResource.java
  rest/src/main/java/com/netflix/conductor/rest/controllers/EventResource.java
  rest/src/main/java/com/netflix/conductor/rest/controllers/TaskResource.java
  rest/src/test/java/com/netflix/conductor/rest/controllers/AdminResourceTest.java
  rest/src/test/java/com/netflix/conductor/rest/controllers/EventResourceTest.java
  rest/src/test/java/com/netflix/conductor/rest/controllers/TaskResourceTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
  test-harness/src/test/java/com/netflix/conductor/test/integration/grpc/AbstractGrpcEndToEndTest.java
  test-harness/src/test/java/com/netflix/conductor/test/integration/http/AbstractHttpEndToEndTest.java
Labels: type: maintenance

#2167 Added publish workflow
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .travis.yml.bak
Labels: skip-changelog

#2171 Customizable lease duration when popping workflow ids from decider queue
  core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowPoller.java
Labels: type: feature

#2169 upload test artifacts and publish test results
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  build.gradle
  core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchRestDAOV6.java
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractResiliencySpecification.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractSpecification.groovy
  test-harness/src/test/resources/application-integrationtest.properties
Labels: skip-changelog

#2181 Ensure async complete system tasks are not response timed out
  .gitignore
  contribs/src/test/java/com/netflix/conductor/contribs/metrics/LoggingMetricsConfigurationTest.java
  contribs/src/test/java/com/netflix/conductor/contribs/metrics/PrometheusMetricsConfigurationTest.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  core/src/test/java/com/netflix/conductor/core/execution/WorkflowSystemTaskStub.java
Labels: type: feature

#2183 Adds sonar to PR builds
  .github/workflows/ci.yml
  azureblob-storage/dependencies.lock
  build.gradle
  cassandra-persistence/dependencies.lock
  client-spring/dependencies.lock
  client/dependencies.lock
  common/dependencies.lock
  contribs/dependencies.lock
  core/dependencies.lock
  dependencies.lock
  es6-persistence/dependencies.lock
  grpc-client/dependencies.lock
  grpc-server/dependencies.lock
  grpc/dependencies.lock
  mysql-persistence/dependencies.lock
  postgres-persistence/dependencies.lock
  redis-lock/dependencies.lock
  redis-persistence/dependencies.lock
  rest/dependencies.lock
  server/dependencies.lock
  test-harness/dependencies.lock
  zookeeper-lock/dependencies.lock
Labels: skip-changelog

#2184 Adding the New Angular Based Web UI for Conductor
  RELATED.md
Labels: skip-changelog

#2172 Renamed WorkflowPoller->WorkflowReconciler and can be enabled using property
  .codecov.yml
  .github/workflows/issues_triage.yml
  .github/workflows/pull_request_triage.yml
  CHANGELOG.md
  build.gradle
  contribs/src/test/java/com/netflix/conductor/contribs/metrics/LoggingMetricsConfigurationTest.java
  contribs/src/test/java/com/netflix/conductor/contribs/metrics/PrometheusMetricsConfigurationTest.java
  contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
  core/src/main/java/com/netflix/conductor/core/config/SchedulerConfiguration.java
  core/src/main/java/com/netflix/conductor/core/events/queue/DefaultEventQueueProcessor.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowReconciler.java
  core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
  core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java
  core/src/main/java/com/netflix/conductor/service/AdminServiceImpl.java
  core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java
  dependencies.lock
  secrets/signing-key.enc
  test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractResiliencySpecification.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractSpecification.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/TaskResiliencySpec.groovy
  test-harness/src/test/resources/application-integrationtest.properties
Labels: type: maintenance
