Repository Netflix/conductor, pull requests merged in 2021-05, with the labels that each got.

#2223 Removed TaskType#isSystemTask in favor SystemTaskRegistry#isSystemTask
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskType.java
  common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Labels: type: maintenance

#2230 Remove workflows from decider queue when paused; add when resumed
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
Labels: type: feature

#2233 Added check for max tasks limit
  .github/release-drafter.yml
  contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
  core/src/main/java/com/netflix/conductor/core/config/SchedulerConfiguration.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/metrics/WorkflowMonitor.java
  core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Labels: type: maintenance

#2249 Get all IP addresses for redis cluster
  redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisClusterConfiguration.java
Labels: type: bug

#2246 bugFix embrace spring flyway
  docker/server/config/config-mysql-grpc.properties
  docker/server/config/config-mysql.properties
  mysql-persistence/build.gradle
  mysql-persistence/src/main/java/com/netflix/conductor/mysql/config/MySQLConfiguration.java
  mysql-persistence/src/main/java/com/netflix/conductor/mysql/config/MySQLDataSourceProvider.java
  mysql-persistence/src/main/java/com/netflix/conductor/mysql/config/MySQLProperties.java
  mysql-persistence/src/test/java/com/netflix/conductor/mysql/dao/MySQLExecutionDAOTest.java
  mysql-persistence/src/test/java/com/netflix/conductor/mysql/dao/MySQLMetadataDAOTest.java
  mysql-persistence/src/test/java/com/netflix/conductor/mysql/dao/MySQLQueueDAOTest.java
  mysql-persistence/src/test/java/com/netflix/conductor/mysql/util/MySQLDAOTestUtil.java
  postgres-persistence/build.gradle
  postgres-persistence/src/main/java/com/netflix/conductor/postgres/config/PostgresConfiguration.java
  postgres-persistence/src/main/java/com/netflix/conductor/postgres/config/PostgresDataSourceProvider.java
  postgres-persistence/src/main/java/com/netflix/conductor/postgres/config/PostgresProperties.java
  postgres-persistence/src/test/java/com/netflix/conductor/postgres/dao/PostgresExecutionDAOTest.java
  postgres-persistence/src/test/java/com/netflix/conductor/postgres/dao/PostgresMetadataDAOTest.java
  postgres-persistence/src/test/java/com/netflix/conductor/postgres/dao/PostgresQueueDAOTest.java
  postgres-persistence/src/test/java/com/netflix/conductor/postgres/util/PostgresDAOTestUtil.java
  server/src/main/java/com/netflix/conductor/Conductor.java
  server/src/main/resources/application.properties
  test-harness/src/test/java/com/netflix/conductor/test/integration/grpc/mysql/MySQLGrpcEndToEndTest.java
  test-harness/src/test/java/com/netflix/conductor/test/integration/grpc/postgres/PostgresGrpcEndToEndTest.java
Labels: type: bug

#2250 Remove workflow operation from task update
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
Labels: type: feature

#2247 Allow retrying timed_out workflow with no unsuccessful tasks
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
Labels: type: feature

#2261 Improve repair service to auto-repair subworkflow
  core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
  core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java
Labels: type: feature

#2264 Add build properties to /admin/config API which is consumed by the UI
  core/src/main/java/com/netflix/conductor/service/AdminServiceImpl.java
  server/build.gradle
Labels: type: bug

#2260 New Search APIs that return Workflow/Task instead of WorkflowSummary/TaskSummary
  client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
  client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
  client/src/test/java/com/netflix/conductor/client/http/TaskClientTest.java
  client/src/test/java/com/netflix/conductor/client/http/WorkflowClientTest.java
  common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java
  core/src/main/java/com/netflix/conductor/service/ExecutionService.java
  core/src/main/java/com/netflix/conductor/service/TaskService.java
  core/src/main/java/com/netflix/conductor/service/TaskServiceImpl.java
  core/src/main/java/com/netflix/conductor/service/WorkflowService.java
  core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
  core/src/test/java/com/netflix/conductor/service/ExecutionServiceTest.java
  core/src/test/java/com/netflix/conductor/service/TaskServiceTest.java
  core/src/test/java/com/netflix/conductor/service/WorkflowServiceTest.java
  grpc-client/src/main/java/com/netflix/conductor/client/grpc/ClientBase.java
  grpc-client/src/main/java/com/netflix/conductor/client/grpc/TaskClient.java
  grpc-client/src/main/java/com/netflix/conductor/client/grpc/WorkflowClient.java
  grpc-client/src/test/java/com/netflix/conductor/client/grpc/TaskClientTest.java
  grpc-client/src/test/java/com/netflix/conductor/client/grpc/WorkflowClientTest.java
  grpc-client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/TaskServiceImpl.java
  grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImpl.java
  grpc-server/src/test/java/com/netflix/conductor/grpc/server/service/TaskServiceImplTest.java
  grpc-server/src/test/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImplTest.java
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  grpc/src/main/proto/grpc/task_service.proto
  grpc/src/main/proto/grpc/workflow_service.proto
  rest/src/main/java/com/netflix/conductor/rest/controllers/TaskResource.java
  rest/src/main/java/com/netflix/conductor/rest/controllers/WorkflowResource.java
  rest/src/test/java/com/netflix/conductor/rest/controllers/TaskResourceTest.java
  rest/src/test/java/com/netflix/conductor/rest/controllers/WorkflowResourceTest.java
  test-harness/src/test/java/com/netflix/conductor/test/integration/grpc/AbstractGrpcEndToEndTest.java
  test-harness/src/test/java/com/netflix/conductor/test/integration/http/AbstractHttpEndToEndTest.java
Labels: type: feature

#2271 #2263 SQL files are the same as 2.31
  mysql-persistence/src/main/resources/db/migration/V1__initial_schema.sql
  mysql-persistence/src/main/resources/db/migration/V2__queue_message_timestamps.sql
  mysql-persistence/src/main/resources/db/migration/V3__queue_add_priority.sql
  mysql-persistence/src/main/resources/db/migration/V4__1009_Fix_MySQLExecutionDAO_Index.sql
  mysql-persistence/src/main/resources/db/migration/V5__correlation_id_index.sql
  mysql-persistence/src/main/resources/db/migration/V6__new_qm_index_with_priority.sql
  mysql-persistence/src/main/resources/db/migration/V7__new_queue_message_pk.sql
  mysql-persistence/src/main/resources/db/migration/V8__update_pk.sql
  postgres-persistence/src/main/resources/db/migration_postgres/V1__initial_schema.sql
  postgres-persistence/src/main/resources/db/migration_postgres/V2__1009_Fix_PostgresExecutionDAO_Index.sql
  postgres-persistence/src/main/resources/db/migration_postgres/V3__correlation_id_index.sql
  postgres-persistence/src/main/resources/db/migration_postgres/V4__new_qm_index_with_priority.sql
  postgres-persistence/src/main/resources/db/migration_postgres/V5__new_queue_message_pk.sql
  postgres-persistence/src/main/resources/db/migration_postgres/V6__update_pk.sql
Labels: type: bug

#2272 Removed task limit
  contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Labels: type: maintenance
