Repository Netflix/conductor, pull requests merged in 2021-12, with the labels that each got.

#2608 Fix startdelay for subworkflow task
  core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
  core/src/test/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapperTest.java
Labels: type: bug

#2636 Force log4j dep version to avoid 0-day exploit
  build.gradle
Labels: type: important

#2610 added nats stream support for WAIT task queues
  contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/config/NATSStreamConfiguration.java
  contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/config/NATSStreamProperties.java
  contribs/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: type: feature

#2646 removed deprecated task acking
  polyglot-clients/python/conductor/ConductorWorker.py
  polyglot-clients/python/conductor/conductor.py
  polyglot-clients/python/test_conductor.py
Labels: type: maintenance

#2674 Bump log4j to 2.17.0 to fix log4shell vulnerability
  contribs/dependencies.lock
  es5-persistence/dependencies.lock
  es6-persistence/dependencies.lock
  es7-persistence/dependencies.lock
  server/dependencies.lock
  test-harness/dependencies.lock
  versionsOfDependencies.gradle
Labels: type: dependencies

#2675 Rework Metrics API to reduce possibility of empty values in tags
  cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraBaseDAO.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorker.java
  core/src/main/java/com/netflix/conductor/metrics/Monitors.java
Labels: type: maintenance
