Repository Netflix/conductor, pull requests merged in 2021-11, with the labels that each got.

#2470 Remove ack from Go client + pass auth to go http client
  polyglot-clients/go/conductorhttpclient.go
  polyglot-clients/go/conductorworker.go
Labels: type: maintenance

#2570 PR for #2548 [FEATURE]: [UI] Adjustable width task panel
  ui/src/components/diagram/WorkflowGraph.jsx
  ui/src/pages/execution/Execution.jsx
Labels: UI

#2593 Adjust dockerfile and associated scripts
  docker/server/Dockerfile
  docker/server/bin/startup.sh
  docker/server/config/config-local.properties
Labels: skip-changelog

#2598 [DOC] Minor documentation changes
  README.md
  docs/docs/architecture.md
  docs/docs/configuration/taskdef.md
  docs/docs/configuration/workflowdef.md
  docs/docs/gettingstarted/basicconcepts.md
Labels: type: docs

#2611 Removed the extra delete statement from removeTaskFromLimit
  cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraExecutionDAO.java
Labels: type: bug
