Repository Netflix/conductor, pull requests merged in 2021-07, with the labels that each got.

#2339 Bulk Terminate API uses POST instead of DELETE
  client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
  rest/src/main/java/com/netflix/conductor/rest/controllers/WorkflowBulkResource.java
  ui/src/api/wfe.js
  ui/src/sagas/bulk.js
Labels: type: bug

#2344 fix for retrying subworkflows within dynamic fork join
  azureblob-storage/dependencies.lock
  build.gradle
  cassandra-persistence/dependencies.lock
  client-spring/dependencies.lock
  client/dependencies.lock
  common/dependencies.lock
  contribs/dependencies.lock
  contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
  core/dependencies.lock
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/metrics/Monitors.java
  dependencies.gradle
  dependencies.lock
  es6-persistence/dependencies.lock
  grpc-client/dependencies.lock
  grpc-server/dependencies.lock
  grpc/dependencies.lock
  mysql-persistence/dependencies.lock
  postgres-persistence/dependencies.lock
  redis-lock/dependencies.lock
  redis-persistence/dependencies.lock
  rest/dependencies.lock
  server/dependencies.lock
  test-harness/dependencies.lock
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
  zookeeper-lock/dependencies.lock
Labels: type: bug

#2353 acquire lock when creating workflow
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
Labels: type: bug

#2349 Feature/separate database services in docker compose
  docker/README.md
  docker/docker-compose-dynomite.yaml
  docker/docker-compose-postgres.yaml
  docker/docker-compose.yaml
  docker/server/config/config-postgres.properties
Labels: type: feature

#2351 add descending priority index to combo_queue_message index to make queue queries faster - 3.x
  postgres-persistence/src/main/resources/db/migration_postgres/V7__new_qm_index_desc_priority.sql
Labels: type: feature

#2352 refactor: use diamond operator
  common/src/main/java/com/netflix/conductor/common/metadata/workflow/DynamicForkJoinTaskList.java
  common/src/test/java/com/netflix/conductor/common/utils/SummaryUtilTest.java
  core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
  es6-persistence/src/main/java/com/netflix/conductor/es6/dao/query/parser/internal/AbstractNode.java
  grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImpl.java
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisExecutionDAO.java
  redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisMetadataDAO.java
  redis-persistence/src/main/java/com/netflix/conductor/redis/jedis/JedisMock.java
  redis-persistence/src/test/java/com/netflix/conductor/redis/jedis/JedisClusterTest.java
  redis-persistence/src/test/java/com/netflix/conductor/redis/jedis/JedisSentinelTest.java
Labels: skip-changelog

#2357 disabled httptasktest; cleaned up WorkflowMonitor
  .github/workflows/ci.yml
  contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
  contribs/src/test/java/com/netflix/conductor/contribs/tasks/json/JsonJqTransformTest.java
  core/src/main/java/com/netflix/conductor/metrics/Monitors.java
  core/src/main/java/com/netflix/conductor/metrics/WorkflowMonitor.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
Labels: skip-changelog

#2360 SubWorkflow task will be auto-retried on BACKEND_ERROR
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
  core/build.gradle
  core/src/main/java/com/netflix/conductor/core/execution/AsyncSystemTaskExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorker.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
  core/src/main/java/com/netflix/conductor/service/ExecutionService.java
  core/src/test/groovy/com/netflix/conductor/core/execution/AsyncSystemTaskExecutorTest.groovy
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSubWorkflow.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorker.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorkerCoordinator.java
  test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractSpecification.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRestartSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRetrySpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/NestedForkJoinSubWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRestartSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRetrySpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SystemTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/TaskLimitsWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
Labels: enhancement, type: feature

#2366 Add callbackAfterSeconds for python client
  polyglot-clients/python/conductor/ConductorWorker.py
Labels: type: feature

#2373 #2256 Updated faq.md for answer on scheduling. Suggestion is to use p…
  docs/docs/faq.md
Labels: skip-changelog
