Repository Netflix/conductor, pull requests merged in 2021-09, with the labels that each got.

#2438 feat: Add inputTemplate support to workflow metadata
  common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/utils/ParametersUtils.java
  core/src/test/java/com/netflix/conductor/core/utils/ParametersUtilsTest.java
  docs/docs/configuration/workflowdef.md
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  grpc/src/main/proto/model/workflowdef.proto
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
  test-harness/src/test/resources/simple_workflow_1_input_template_integration_test.json
Labels: enhancement, type: feature

#2458 Fix Conductor Artifacts Link
  README.md
Labels: type: docs

#2439 fix client delete method
  client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
  client/src/test/java/com/netflix/conductor/client/http/MetadataClientTest.java
Labels: type: bug

#2487 jackson-jq upgrade
  contribs/dependencies.lock
  dependencies.gradle
  server/dependencies.lock
  test-harness/dependencies.lock
Labels: type: dependencies
