Repository Netflix/conductor, pull requests merged in 2022-06, with the labels that each got.

#3029 Typo fix
  docs/docs/faq.md
Labels: type: docs

#3024 Introducing RequestHandler in the client module, which encapsulates all HTTP operations
  annotations-processor/dependencies.lock
  annotations/dependencies.lock
  awss3-storage/dependencies.lock
  awssqs-event-queue/dependencies.lock
  build.gradle
  cassandra-persistence/dependencies.lock
  client-spring/dependencies.lock
  client/build.gradle
  client/dependencies.lock
  client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
  client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
  client/src/main/java/com/netflix/conductor/client/exception/RequestHandlerException.java
  client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
  client/src/main/java/com/netflix/conductor/client/http/EventClient.java
  client/src/main/java/com/netflix/conductor/client/http/MetadataClient.java
  client/src/main/java/com/netflix/conductor/client/http/PayloadStorage.java
  client/src/main/java/com/netflix/conductor/client/http/RequestHandler.java
  client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
  client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
  client/src/main/java/com/netflix/conductor/client/http/jersey/JerseyRequestHandler.java
  client/src/main/java/com/netflix/conductor/client/telemetry/MetricsContainer.java
  client/src/test/groovy/com/netflix/conductor/client/http/ClientSpecification.groovy
  client/src/test/groovy/com/netflix/conductor/client/http/EventClientSpec.groovy
  client/src/test/groovy/com/netflix/conductor/client/http/MetadataClientSpec.groovy
  client/src/test/groovy/com/netflix/conductor/client/http/TaskClientSpec.groovy
  client/src/test/groovy/com/netflix/conductor/client/http/WorkflowClientSpec.groovy
  client/src/test/java/com/netflix/conductor/client/automator/TaskRunnerConfigurerTest.java
  client/src/test/java/com/netflix/conductor/client/http/EventClientTest.java
  client/src/test/java/com/netflix/conductor/client/http/MetadataClientTest.java
  client/src/test/java/com/netflix/conductor/client/http/PayloadStorageTest.java
  client/src/test/java/com/netflix/conductor/client/http/TaskClientTest.java
  client/src/test/java/com/netflix/conductor/client/http/WorkflowClientTest.java
  common/dependencies.lock
  core/dependencies.lock
  dependencies.lock
  es6-persistence/dependencies.lock
  grpc-client/dependencies.lock
  grpc-server/dependencies.lock
  grpc/dependencies.lock
  http-task/dependencies.lock
  java-sdk/dependencies.lock
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/WorkflowExecutor.java
  json-jq-task/dependencies.lock
  redis-concurrency-limit/dependencies.lock
  redis-lock/dependencies.lock
  redis-persistence/dependencies.lock
  rest/dependencies.lock
  rest/src/main/java/com/netflix/conductor/rest/controllers/ValidationExceptionMapper.java
  server/dependencies.lock
  server/src/main/java/com/netflix/conductor/Conductor.java
  test-harness/dependencies.lock
Labels: type: important

#3075 Improve message for payload size threshold calculation
  core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
Labels: type: bug
