Repository Netflix/conductor, pull requests merged in 2022-03, with the labels that each got.

#2798 Fix the path to architecture diagram
  docs/docs/architecture.md
Labels: type: docs

#2832 Update WHOSUSING.md
  WHOSUSING.md
Labels: skip-changelog

#2831 Update workflowdef.md
  docs/docs/configuration/workflowdef.md
Labels: type: docs

#2837 Update archival-of-workflows.md
  docs/docs/how-tos/archival-of-workflows.md
Labels: type: docs

#2807 Added support for sub workflow in loop task
  core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
  core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
  test-harness/src/test/resources/do_while_sub_workflow_integration_test.json
Labels: type: feature

#2804 DO_WHILE improvement - Check only for current iteration task to get completed.
  core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
Labels: type: maintenance

#2857 Golang client updates
  polyglot-clients/go/conductorhttpclient.go
  polyglot-clients/go/conductorworker.go
  polyglot-clients/go/go.mod
  polyglot-clients/go/go.sum
  polyglot-clients/go/httpclient/httpclient.go
  polyglot-clients/go/startclient/startclient.go
  polyglot-clients/go/task/sample/task_1_exec.go
  polyglot-clients/go/task/taskresult.go
Labels: type: maintenance

#2864 Ensure that input/output are correctly represented in transfer objects
  core/src/main/java/com/netflix/conductor/model/TaskModel.java
  core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
Labels: type: maintenance
