Repository Netflix/conductor, pull requests merged in 2022-07, with the labels that each got.

#3079 Cap retryCount limit to 10
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
Labels: type: feature

#3091 Added metric for ExecutionLockService and the decide process, workflow_decision
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/metrics/Monitors.java
  core/src/main/java/com/netflix/conductor/service/ExecutionLockService.java
Labels: type: feature

#3096 Set size limit for task exec log and add metrics
  core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java
  core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
  core/src/main/java/com/netflix/conductor/metrics/Monitors.java
Labels: type: feature

#3111 Fix typo: persistance → persistence
  docs/docs/gettingstarted/source.md
  docs/docs/index.md
  docs/docs/reference-docs/azureblob-storage.md
Labels: type: docs

#3114 For INLINE task, reasonForIncompletion field includes the script evaluation error message
  core/src/main/java/com/netflix/conductor/core/execution/evaluators/JavascriptEvaluator.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Inline.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/InlineTest.java
Labels: type: bug

#3108 API (/workflow/validate) to validate a workflow definition
  client/src/main/java/com/netflix/conductor/client/http/MetadataClient.java
  common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
  core/src/main/java/com/netflix/conductor/service/MetadataService.java
  core/src/main/java/com/netflix/conductor/service/MetadataServiceImpl.java
  core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
  grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/MetadataServiceImpl.java
  grpc/src/main/proto/grpc/metadata_service.proto
  rest/src/main/java/com/netflix/conductor/rest/controllers/MetadataResource.java
  rest/src/test/java/com/netflix/conductor/rest/controllers/MetadataResourceTest.java
Labels: type: feature

#3118 When a task is updated only the workflow is loaded, not all of its tasks
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Labels: type: maintenance
