Repository Netflix/conductor, pull requests merged in 2022-09, with the labels that each got.

#3207 Extract json node body from json_jq task output
  json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
  json-jq-task/src/test/java/com/netflix/conductor/tasks/json/JsonJqTransformTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy
  test-harness/src/test/resources/json_jq_transform_result_integration_test.json
Labels: type: bug

#3214 Combined input/output data if additional payload is added when update…
  core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
  core/src/main/java/com/netflix/conductor/model/TaskModel.java
  core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
  core/src/test/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtilsTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/util/WorkflowTestUtil.groovy
  test-harness/src/test/java/com/netflix/conductor/test/utils/MockExternalPayloadStorage.java
Labels: type: bug

#3225 Handle null results in json jq task script evaluation
  json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
  json-jq-task/src/test/java/com/netflix/conductor/tasks/json/JsonJqTransformTest.java
Labels: type: bug

#3232 Fix subworkflow output during repair
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
  core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
  core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java
Labels: type: bug

#3231 Fix missing updateTime because of different field names in WorkflowModel and Workflow
  core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
Labels: type: bug

#3236 Removed usages of TaskModel#getOutputData().put()
  core/src/main/java/com/netflix/conductor/core/events/SimpleActionProcessor.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Event.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Inline.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Lambda.java
  core/src/main/java/com/netflix/conductor/model/TaskModel.java
  core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/EventQueueResolutionTest.java
  core/src/test/java/com/netflix/conductor/dao/ExecutionDAOTest.java
  http-task/src/main/java/com/netflix/conductor/tasks/http/HttpTask.java
Labels: skip-changelog

#3196 Adding parameterUtils in do-while task to compute input at each iteration.
  core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
  core/src/test/groovy/com/netflix/conductor/core/execution/tasks/DoWhileSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
  test-harness/src/test/resources/do_while_set_variable_fix.json
Labels: type: bug

#3242 Refactor bulk updateWorkflowDefs API to return list of success/failur…
  core/src/main/java/com/netflix/conductor/service/MetadataService.java
  core/src/main/java/com/netflix/conductor/service/MetadataServiceImpl.java
  rest/src/main/java/com/netflix/conductor/rest/controllers/MetadataResource.java
Labels: type: important

#3221 Update workflow in DAO in case of update of workflow related attribute.
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SetVariable.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/WaitTaskSpec.groovy
  test-harness/src/test/resources/set_variable_workflow_integration_test.json
Labels: type: bug

#3237 Introduced access policy in WorkflowDef and TaskDef
  common/src/main/java/com/netflix/conductor/common/metadata/BaseDef.java
  common/src/main/java/com/netflix/conductor/common/metadata/acl/Permission.java
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
  common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
  core/src/main/java/com/netflix/conductor/core/events/SimpleActionProcessor.java
  core/src/main/java/com/netflix/conductor/core/execution/StartWorkflowInput.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/StartWorkflow.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
  core/src/main/java/com/netflix/conductor/service/WorkflowService.java
  core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
  core/src/test/java/com/netflix/conductor/core/events/TestDefaultEventProcessor.java
  core/src/test/java/com/netflix/conductor/core/events/TestSimpleActionProcessor.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSubWorkflow.java
  core/src/test/java/com/netflix/conductor/service/WorkflowServiceTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractSpecification.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DecisionTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/EventTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExclusiveJoinSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/FailureWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRerunSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRestartSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRetrySpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/NestedForkJoinSubWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SetVariableTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/StartWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRerunSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRestartSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRetrySpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SwitchTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SystemTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/TaskLimitsWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/WaitTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/TaskResiliencySpec.groovy
Labels: skip-changelog
