Repository Netflix/conductor, pull requests merged in 2022-08, with the labels that each got.

#3183 Repair inconsistent subworkflow task
  core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
  core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java
Labels: type: bug

#3187 Split event system task implementation between start and execute
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Event.java
  core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
  core/src/test/groovy/com/netflix/conductor/core/execution/tasks/EventSpec.groovy
  core/src/test/java/com/netflix/conductor/core/execution/tasks/EventQueueResolutionTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/EventTaskSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/util/WorkflowTestUtil.groovy
Labels: type: bug

#3185 Failed task names
  common/src/main/java/com/netflix/conductor/common/run/Workflow.java
  common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  es6-persistence/src/main/resources/mappings_docType_workflow.json
  es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchDAOV6.java
  es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchRestDAOV6.java
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  grpc/src/main/proto/model/workflow.proto
  grpc/src/main/proto/model/workflowsummary.proto
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
Labels: type: feature

#3188 Add task domain to the index
  common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java
  es6-persistence/src/main/resources/mappings_docType_task.json
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  grpc/src/main/proto/model/tasksummary.proto
Labels: type: feature

#3186 task lease extend
  client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
  client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
  client/src/main/java/com/netflix/conductor/client/telemetry/MetricsContainer.java
  client/src/main/java/com/netflix/conductor/client/worker/Worker.java
  client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
  core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/metrics/Monitors.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Labels: type: feature

#3190 Extract map body from json_jq output
  json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
  json-jq-task/src/test/java/com/netflix/conductor/tasks/json/JsonJqTransformTest.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy
  test-harness/src/test/resources/sequential_json_jq_transform_integration_test.json
Labels: type: bug

#3074 updated polyglot-client directory
  polyglot-clients/README.md
  polyglot-clients/go/README.md
  polyglot-clients/go/conductorhttpclient.go
  polyglot-clients/go/conductorworker.go
  polyglot-clients/go/go.mod
  polyglot-clients/go/go.sum
  polyglot-clients/go/httpclient/httpclient.go
  polyglot-clients/go/startclient/startclient.go
  polyglot-clients/go/task/sample/task_1_exec.go
  polyglot-clients/go/task/sample/task_2_exec.go
  polyglot-clients/go/task/task.go
  polyglot-clients/go/task/task_exec_template.go
  polyglot-clients/go/task/taskresult.go
  polyglot-clients/gogrpc/.gitignore
  polyglot-clients/gogrpc/Gopkg.lock
  polyglot-clients/gogrpc/Gopkg.toml
  polyglot-clients/gogrpc/Makefile
  polyglot-clients/gogrpc/README.md
  polyglot-clients/gogrpc/conductor/client.go
  polyglot-clients/gogrpc/conductor/grpc/events/event_service.pb.go
  polyglot-clients/gogrpc/conductor/grpc/metadata/metadata_service.pb.go
  polyglot-clients/gogrpc/conductor/grpc/search/search.pb.go
  polyglot-clients/gogrpc/conductor/grpc/tasks/task_service.pb.go
  polyglot-clients/gogrpc/conductor/grpc/workflows/workflow_service.pb.go
  polyglot-clients/gogrpc/conductor/model/dynamicforkjointask.pb.go
  polyglot-clients/gogrpc/conductor/model/dynamicforkjointasklist.pb.go
  polyglot-clients/gogrpc/conductor/model/eventexecution.pb.go
  polyglot-clients/gogrpc/conductor/model/eventhandler.pb.go
  polyglot-clients/gogrpc/conductor/model/polldata.pb.go
  polyglot-clients/gogrpc/conductor/model/rerunworkflowrequest.pb.go
  polyglot-clients/gogrpc/conductor/model/skiptaskrequest.pb.go
  polyglot-clients/gogrpc/conductor/model/startworkflowrequest.pb.go
  polyglot-clients/gogrpc/conductor/model/subworkflowparams.pb.go
  polyglot-clients/gogrpc/conductor/model/task.pb.go
  polyglot-clients/gogrpc/conductor/model/taskdef.pb.go
  polyglot-clients/gogrpc/conductor/model/taskexeclog.pb.go
  polyglot-clients/gogrpc/conductor/model/taskresult.pb.go
  polyglot-clients/gogrpc/conductor/model/tasksummary.pb.go
  polyglot-clients/gogrpc/conductor/model/workflow.pb.go
  polyglot-clients/gogrpc/conductor/model/workflowdef.pb.go
  polyglot-clients/gogrpc/conductor/model/workflowsummary.pb.go
  polyglot-clients/gogrpc/conductor/model/workflowtask.pb.go
  polyglot-clients/gogrpc/conductor/worker.go
  polyglot-clients/gogrpc/conductor/worker_test.go
  polyglot-clients/gogrpc/go.mod
  polyglot-clients/gogrpc/go.sum
  polyglot-clients/gogrpc/tools.go
  polyglot-clients/python/.gitignore
  polyglot-clients/python/README.md
  polyglot-clients/python/conductor/ConductorWorker.py
  polyglot-clients/python/conductor/__init__.py
  polyglot-clients/python/conductor/conductor.py
  polyglot-clients/python/conductor_shell.py
  polyglot-clients/python/kitchensink_workers.py
  polyglot-clients/python/setup.cfg
  polyglot-clients/python/setup.py
  polyglot-clients/python/test_conductor.py
Labels: type: important

#3200 [Docs] Fixed Language issues.
  docs/docs/configuration/workflowdef.md
  docs/docs/resources/contributing.md
  ui/README.md
Labels: type: docs
