Repository Netflix/conductor, pull requests merged in 2022-02, with the labels that each got.

#2739 Sub workflow / parent workflow interaction fix
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Labels: type: bug

#2745 use domain models in default queues
  client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
  contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/config/AMQPEventQueueConfiguration.java
  contribs/src/main/java/com/netflix/conductor/contribs/queue/sqs/config/SQSEventQueueConfiguration.java
  contribs/src/test/java/com/netflix/conductor/contribs/queue/sqs/DefaultEventQueueProcessorTest.java
  core/src/main/java/com/netflix/conductor/core/dal/ModelMapper.java
  core/src/main/java/com/netflix/conductor/core/events/DefaultEventQueueManager.java
  core/src/main/java/com/netflix/conductor/core/events/queue/DefaultEventQueueProcessor.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/SetVariable.java
  core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
  core/src/main/java/com/netflix/conductor/model/TaskModel.java
  core/src/test/groovy/com/netflix/conductor/core/dal/ModelMapperSpec.groovy
  rest/src/main/java/com/netflix/conductor/rest/controllers/QueueAdminResource.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/SetVariableTaskSpec.groovy
Labels: type: maintenance

#2747 Update WHOSUSING.md
  WHOSUSING.md
Labels: skip-changelog

#2685 Fix for failure workflow
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/FailureWorkflowSpec.groovy
  test-harness/src/test/resources/test_task_failed_parent_workflow.json
  test-harness/src/test/resources/test_task_failed_sub_workflow.json
Labels: type: feature

#2761 sub workflow / parent workflow interaction fix
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Labels: type: bug

#2771 add termination reason param to terminate task
  .github/release-drafter.yml
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Terminate.java
  docs/docs/configuration/systask.md
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/FailureWorkflowSpec.groovy
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
  test-harness/src/test/resources/terminate_task_failed_workflow_integration.json
Labels: type: feature

#2795 Update apispec.md - remove ack API mention
  docs/docs/apispec.md
Labels: type: docs
