Repository Netflix/conductor, pull requests merged in 2022-01, with the labels that each got.

#2680 Updated openapi version to 1.6.+
  annotations-processor/dependencies.lock
  annotations/dependencies.lock
  azureblob-storage/dependencies.lock
  cassandra-persistence/dependencies.lock
  client-spring/dependencies.lock
  client/dependencies.lock
  common/dependencies.lock
  contribs/dependencies.lock
  core/dependencies.lock
  dependencies.gradle
  dependencies.lock
  es6-persistence/dependencies.lock
  es7-persistence/dependencies.lock
  grpc-client/dependencies.lock
  grpc-server/dependencies.lock
  grpc/dependencies.lock
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  grpc/src/main/proto/model/taskdef.proto
  mysql-persistence/dependencies.lock
  postgres-persistence/dependencies.lock
  redis-concurrency-limit/dependencies.lock
  redis-lock/dependencies.lock
  redis-persistence/dependencies.lock
  rest/dependencies.lock
  server/dependencies.lock
  test-harness/dependencies.lock
  zookeeper-lock/dependencies.lock
Labels: type: dependencies

#2683 Implement PSQL based object storage for Conductor
  core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  docs/docs/externalpayloadstorage.md
  postgres-external-storage/README.md
  postgres-external-storage/build.gradle
  postgres-external-storage/dependencies.lock
  postgres-external-storage/src/main/java/com/netflix/conductor/postgres/config/PostgresPayloadConfiguration.java
  postgres-external-storage/src/main/java/com/netflix/conductor/postgres/config/PostgresPayloadProperties.java
  postgres-external-storage/src/main/java/com/netflix/conductor/postgres/controller/ExternalPostgresPayloadResource.java
  postgres-external-storage/src/main/java/com/netflix/conductor/postgres/storage/PostgresPayloadStorage.java
  postgres-external-storage/src/main/resources/db/migration_external_postgres/R__initial_schema.sql
  postgres-external-storage/src/test/java/com/netflix/conductor/postgres/controller/ExternalPostgresPayloadResourceTest.java
  postgres-external-storage/src/test/java/com/netflix/conductor/postgres/storage/PostgresPayloadStorageTest.java
  postgres-external-storage/src/test/java/com/netflix/conductor/postgres/storage/PostgresPayloadTestUtil.java
  postgres-persistence/src/main/java/com/netflix/conductor/postgres/config/PostgresConfiguration.java
  server/build.gradle
  settings.gradle
Labels: type: feature

#2704 Hide com.google.protobuf.Any from Swagger introspection
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
  common/src/main/java/com/netflix/conductor/common/metadata/workflow/SkipTaskRequest.java
Labels: type: bug, type: maintenance

#2688 Bug 2678- tcp protocol support for es6
  es6-persistence/src/main/java/com/netflix/conductor/es6/config/ElasticSearchV6Configuration.java
  es6-persistence/src/main/java/com/netflix/conductor/es6/config/IsHttpProtocol.java
  es6-persistence/src/main/java/com/netflix/conductor/es6/config/IsTcpProtocol.java
Labels: type: bug

#2699 Support for Retry with LINEAR_BACKOFF
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
  docs/docs/configuration/taskdef.md
  grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
  grpc/src/main/proto/model/taskdef.proto
Labels: type: feature

#2664 Build tools upgrade
  annotations-processor/build.gradle
  build.gradle
  core/src/main/java/com/netflix/conductor/service/AdminServiceImpl.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  server/build.gradle
  server/src/main/resources/application.properties
  test-harness/src/test/java/com/netflix/conductor/ConductorTestApp.java
  test-harness/src/test/resources/application-integrationtest.properties
Labels: gradle-wrapper
