Repository Netflix/conductor, pull requests merged in 2022-05, with the labels that each got.

#2954 Add an ack request for each task polled from queue, when polling in batches
  core/src/main/java/com/netflix/conductor/service/ExecutionService.java
Labels: type: feature

#2962 fixed typos
  docs/docs/configuration/workflowdef.md
Labels: skip-changelog

#2964 Fix for NPE when header values are null
  http-task/src/main/java/com/netflix/conductor/tasks/http/HttpTask.java
Labels: type: bug

#2965 Update documentation for loop task (DO_WHILE)
  docs/docs/reference-docs/do-while-task.md
Labels: type: docs

#2950 Redis password authentication support
  docs/docs/how-tos/redis.md
  redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisClusterConfiguration.java
  redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisSentinelConfiguration.java
  redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisStandaloneConfiguration.java
  server/src/main/resources/application.properties
Labels: type: feature

#2963 Add visual Loop representation.
  ui/src/components/diagram/WorkflowDAG.js
  ui/src/components/diagram/WorkflowGraph.jsx
  ui/src/components/diagram/diagram.scss
  ui/src/pages/execution/Timeline.jsx
Labels: UI, type: feature

#2973 only allow rerun on terminal workflows
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/service/ExecutionService.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Labels: type: feature

#2980 Delete question.md
  .github/ISSUE_TEMPLATE/question.md
Labels: skip-changelog

#2982 Fix update with large payload task result
  client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
  client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
  client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
Labels: type: bug

#2934 Upgrade to Spring Boot 2.6.6
  annotations-processor/dependencies.lock
  annotations/dependencies.lock
  awss3-storage/dependencies.lock
  awssqs-event-queue/dependencies.lock
  build.gradle
  cassandra-persistence/dependencies.lock
  client-spring/dependencies.lock
  client/dependencies.lock
  common/dependencies.lock
  core/dependencies.lock
  dependencies.gradle
  dependencies.lock
  es6-persistence/dependencies.lock
  grpc-client/dependencies.lock
  grpc-server/dependencies.lock
  grpc/dependencies.lock
  http-task/dependencies.lock
  java-sdk/build.gradle
  java-sdk/dependencies.lock
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/WorkflowCreationTests.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/testing/WorkflowTestFrameworkTests.java
  json-jq-task/dependencies.lock
  managed-version-overrides.gradle
  redis-concurrency-limit/dependencies.lock
  redis-lock/dependencies.lock
  redis-persistence/dependencies.lock
  rest/dependencies.lock
  server/build.gradle
  server/dependencies.lock
  test-harness/dependencies.lock
Labels: type: dependencies

#2974 Optional subworkflow task
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Join.java
  core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
  core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
  docs/docs/reference-docs/sub-workflow-task.md
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
Labels: type: bug

#3004 Log workflow failures
  core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
  core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Labels: type: maintenance

#2987 Human Task
  common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskType.java
  core/src/main/java/com/netflix/conductor/core/execution/mapper/HumanTaskMapper.java
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Human.java
  core/src/test/java/com/netflix/conductor/core/execution/mapper/HumanTaskMapperTest.java
Labels: type: feature

#2986 Enhance WAIT task to support time-based wait scenarios
  core/src/main/java/com/netflix/conductor/core/execution/tasks/Wait.java
  core/src/main/java/com/netflix/conductor/core/utils/DateTimeUtils.java
  core/src/main/java/com/netflix/conductor/model/TaskModel.java
  core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
  core/src/test/java/com/netflix/conductor/core/execution/tasks/TestWait.java
  docs/docs/reference-docs/wait-task.md
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Wait.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/TaskConversionsTests.java
  polyglot-clients/README.md
Labels: type: feature
