Repository Netflix/conductor, pull requests merged in 2022-04, with the labels that each got.

#2657 integ test for dynamic fork with subworkflow external storage
  test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
  test-harness/src/test/java/com/netflix/conductor/test/utils/MockExternalPayloadStorage.java
  test-harness/src/test/resources/dynamic_fork_join_integration_test.json
Labels: type: maintenance

#2856 Workflow as Code SDK for Conductor
  java-sdk/README.md
  java-sdk/build.gradle
  java-sdk/example/java/com/netflix/conductor/sdk/example/shipment/Order.java
  java-sdk/example/java/com/netflix/conductor/sdk/example/shipment/Shipment.java
  java-sdk/example/java/com/netflix/conductor/sdk/example/shipment/ShipmentState.java
  java-sdk/example/java/com/netflix/conductor/sdk/example/shipment/ShipmentWorkers.java
  java-sdk/example/java/com/netflix/conductor/sdk/example/shipment/ShipmentWorkflow.java
  java-sdk/example/java/com/netflix/conductor/sdk/example/shipment/User.java
  java-sdk/example/resources/script.js
  java-sdk/src/main/java/com/netflix/conductor/sdk/healthcheck/HealthCheckClient.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/testing/LocalServerRunner.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/testing/WorkflowTestRunner.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/ConductorWorkflow.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/ValidationError.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/WorkflowBuilder.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/DoWhile.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Dynamic.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/DynamicFork.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/DynamicForkInput.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Event.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/ForkJoin.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Http.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/JQ.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Javascript.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Join.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/SetVariable.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/SimpleTask.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/SubWorkflow.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Switch.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Task.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/TaskRegistry.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Terminate.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/def/tasks/Wait.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/WorkflowExecutor.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorker.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerExecutor.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/DynamicForkWorker.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/task/InputParam.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/task/OutputParam.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/task/WorkerTask.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/utils/InputOutputGetter.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/utils/MapBuilder.java
  java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/utils/ObjectMapperProvider.java
  java-sdk/src/main/resources/test-server.properties
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/TaskConversionsTests.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/WorkflowCreationTests.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/WorkflowState.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/testing/Task1Input.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/testing/TestWorkflowInput.java
  java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/testing/WorkflowTestFrameworkTests.java
  java-sdk/src/test/resources/application-integrationtest.properties
  java-sdk/src/test/resources/log4j2.xml
  java-sdk/src/test/resources/script.js
  java-sdk/src/test/resources/simple_workflow.json
  java-sdk/src/test/resources/tasks.json
  java-sdk/testing_framework.md
  java-sdk/worker_sdk.md
  java-sdk/workflow_sdk.md
  settings.gradle
Labels: type: important

#2900 Fix credentials for es6
  es6-persistence/src/main/java/com/netflix/conductor/es6/config/ElasticSearchProperties.java
  es6-persistence/src/main/java/com/netflix/conductor/es6/config/ElasticSearchV6Configuration.java
Labels: type: feature

#2895 Disable ES in local docker config
  docker/server/config/config-local.properties
Labels: type: bug

#2905 ignore codes raised by new spotbugs
  client/build.gradle
  client/spotbugsExclude.xml
Labels: skip-changelog

#2929 #2913 fixed dead links
  docs/docs/architecture.md
Labels: type: docs

#2922 Set permissions for GitHub actions
  .github/workflows/publish.yml
  .github/workflows/release_draft.yml
  .github/workflows/stale.yml
Labels: skip-changelog

#2920 SQL to SQS eventing name
  docs/docs/reference-docs/event-task.md
Labels: skip-changelog

#2933 Reinstated the null check for TaskModel
  core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
Labels: type: bug

#2953 Corrected the tokenization logic in CassandraMetadataDAO
  cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraMetadataDAO.java
  cassandra-persistence/src/test/groovy/com/netflix/conductor/cassandra/dao/CassandraMetadataDAOSpec.groovy
Labels: type: bug
