Repository Netflix/conductor, pull requests merged in 2023-01, with the labels that each got.

#3398 Use AmazonSQS instead of AmazonSQSClient
  awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueConfiguration.java
  awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueProvider.java
  awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/eventqueue/SQSObservableQueue.java
  awssqs-event-queue/src/test/java/com/netflix/conductor/sqs/eventqueue/SQSObservableQueueTest.java
Labels: type: maintenance

#3452 Update README.md
  README.md
Labels: type: docs

#3376 add support compilation on m1 mac
  grpc/build.gradle
Labels: type: dependencies, Stale

#3418 Improve Java Worker documentation
  docs/docs/how-tos/Workers/build-a-java-task-worker.md
Labels: type: docs

#3441 Update the docs for external payload storage to match the code
  docs/docs/externalpayloadstorage.md
Labels: type: docs

#3383 feature: Add option to add payloadBytes into getLocation method
  common/src/main/java/com/netflix/conductor/common/utils/ExternalPayloadStorage.java
  core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
  core/src/test/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtilsTest.java
Labels: type: feature, Stale
